### ISSUE TITLE
The installation package encountered an error and could not be installed. How to fix this error

### ISSUE THREAD

**Issue by shan-see** [rpkgs/spInterp#1]
Downloading GitHub repo rpkgs/spInterp@HEAD
Error: Failed to install 'spInterp' from GitHub:
  input string 62 is invalid
In addition: Warning message:
In gsub("[^/]", "", file_list) :
  unable to translate 'rpkgs-spInterp-4386c71/inst/anusplin_doc/执<e8>\241\214方式.txt' to a wide string
![微信截图_20230710181735](https://github.com/rpkgs/spInterp/assets/60803580/1d1c1457-63cd-4d1d-9a4b-cb70941a33be)

**Comment by kongdd** [comment]
fixed by the latest commit
